# See https://docs.github.com/en/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: ci

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [8, 11, 17, 21]
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'

      - name: Build
        run: mvn -B package javadoc:javadoc

  coverage:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'zulu'

      - name: Build with coverage
        run: mvn -B -Pcoverage clean test jacoco:report-aggregate

      - name: Publish coverage
        uses: codecov/codecov-action@v1

  android-compatibility:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          java-version: 8
          distribution: 'zulu'

      - name: Android Lint checks
        run: cd commonmark-android-test && ./gradlew :app:lint
